# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 17:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160611_1304'),
    ]

    operations = [
    ]
